local wezterm = require('wezterm')

return {
  audible_bell = 'Disabled',
  check_for_updates = false,
  color_scheme = 'Monokai (base16)',
  default_cursor_style = 'SteadyBlock',
  disable_default_key_bindings = false,
  enable_scroll_bar = true,
  font = wezterm.font_with_fallback {'DejaVu Sans Mono', 'Courier New',},
  font_size = 12.0,
  hide_tab_bar_if_only_one_tab = true,
  scrollback_lines = 3500,
  window_close_confirmation = 'NeverPrompt',
  window_background_opacity = 1.0,

  -- Disable ligatures
  harfbuzz_features = { 'calt=0', 'clig=0', 'liga=0' },

  -- Leader key
  leader = { key = '`', timeout_milliseconds = 9000 },
  -- Key bindings
  keys = {
    -- Send "`" to the terminal when pressing "`", "`"
    {key = '`', mods="LEADER",
      action=wezterm.action{SendString='`'}},
    {key = 'o', mods="LEADER",
      action=wezterm.action{SplitVertical={domain="CurrentPaneDomain"}}},
    {key = 'v', mods="LEADER",
      action=wezterm.action{SplitHorizontal={domain="CurrentPaneDomain"}}},
    {key = 't', mods="LEADER",
      action=wezterm.action{SpawnTab="CurrentPaneDomain"}},
    {key = 'n', mods="LEADER",
      action=wezterm.action.ActivateTabRelative(1)},
    {key = 'p', mods="LEADER",
      action=wezterm.action.ActivateTabRelative(-1)},
    {key = 'q', mods="LEADER",
      action=wezterm.action.CloseCurrentTab{confirm = false }},
    {key = 'h', mods="LEADER",
      action=wezterm.action{ActivatePaneDirection="Left"}},
    {key = 'l', mods="LEADER",
      action=wezterm.action{ActivatePaneDirection="Right"}},
    {key = 'k', mods="LEADER",
      action=wezterm.action{ActivatePaneDirection="Up"}},
    {key = 'j', mods="LEADER",
      action=wezterm.action{ActivatePaneDirection="Down"}},
    {key = 'w', mods="LEADER",
      action=wezterm.action.CloseCurrentPane{confirm = false}},
    {key = 'z', mods="LEADER",
      action="TogglePaneZoomState"},
    {key = 'f', mods="LEADER",
      action="ToggleFullScreen"},
    {key = 'a', mods="LEADER",
      action="ActivateCopyMode"},
    {key = 'UpArrow', mods="CTRL",
      action=wezterm.action.ScrollByPage(-0.5)},
    {key = 'DownArrow', mods="CTRL",
      action=wezterm.action.ScrollByPage(0.5)},
  },
}
