local wezterm = require('wezterm')
local act = wezterm.action

return {
  audible_bell = 'Disabled',
  check_for_updates = false,
  color_scheme = 'Monokai (base16)',
  default_cursor_style = 'SteadyBlock',
  disable_default_key_bindings = true,
  enable_scroll_bar = true,
  font = wezterm.font_with_fallback {'DejaVu Sans Mono', 'Courier New',},
  font_size = 12.0,
  hide_tab_bar_if_only_one_tab = true,
  scrollback_lines = 3500,
  window_close_confirmation = 'NeverPrompt',
  window_background_opacity = 1.0,

  -- Disable ligatures
  harfbuzz_features = { 'calt=0', 'clig=0', 'liga=0' },

  -- Key bindings
  keys = {
    {key = 'o', mods="ALT",
      action=act{SplitVertical={domain="CurrentPaneDomain"}}},
    {key = 'v', mods="ALT",
      action=act{SplitHorizontal={domain="CurrentPaneDomain"}}},
    {key = 't', mods="ALT",
      action=act{SpawnTab="CurrentPaneDomain"}},
    {key = 'n', mods="ALT",
      action=act.ActivateTabRelative(1)},
    {key = 'p', mods="ALT",
      action=act.ActivateTabRelative(-1)},
    {key = 'q', mods="ALT",
      action=act.CloseCurrentTab{confirm = false }},
    {key = 'h', mods="ALT",
      action=act{ActivatePaneDirection="Left"}},
    {key = 'l', mods="ALT",
      action=act{ActivatePaneDirection="Right"}},
    {key = 'k', mods="ALT",
      action=act{ActivatePaneDirection="Up"}},
    {key = 'j', mods="ALT",
      action=act{ActivatePaneDirection="Down"}},
    {key = 'w', mods="ALT",
      action=act.CloseCurrentPane{confirm = false}},
    {key = 'z', mods="ALT",
      action="TogglePaneZoomState"},
    {key = 'f', mods="ALT",
      action="ToggleFullScreen"},
    {key = 'a', mods="ALT",
      action="ActivateCopyMode"},
    {key = 'UpArrow', mods="CTRL",
      action=act.ScrollByPage(-0.5)},
    {key = 'DownArrow', mods="CTRL",
      action=act.ScrollByPage(0.5)},
    {key = 'c', mods="CTRL",
      action=act.CopyTo("ClipboardAndPrimarySelection")},
    {key = 'v', mods="CTRL",
      action=act.PasteFrom("Clipboard")},
    {key = 'v', mods="CTRL",
      action=act.PasteFrom("PrimarySelection")},
    {key = 'F', mods="CTRL",
      action=act.Search{CaseInSensitiveString=""}},
  },
}
