local utils = require('utils')

utils.map("n", "<leader>ss", function()
    require("persistence").save()
end, { desc = "Save session" })
utils.map("n", "<leader>sl", function()
    require("persistence").load({ last = true })
end, { desc = "Restore last session" })
utils.map("n", "<leader>sr", function()
    require("persistence").select()
end, { desc = "Select session to restore" })
utils.map("n", "<leader>sq", function()
    require("persistence").stop()
end, { desc = "Stop persistence" })
