- clean: ['~']

- link:
    ~/.bash_profile: bash_profile
    ~/.bashrc: bashrc
    ~/.dircolors: dircolors
    ~/.config/nvim: nvim
    ~/.gitconfig: gitconfig

- shell:
    - [git submodule update --init --recursive, Installing submodules]
