- clean: ['~']

- link:
    ~/.bash_profile: bash_profile
    ~/.bashrc: bashrc
    ~/.bashrc_linux: bashrc_linux
    ~/.bashrc_mac: bashrc_mac
    ~/.config/nvim: nvim
    ~/.config/wezterm: wezterm
    ~/.dircolors: dircolors
    ~/.gitconfig: gitconfig
    ~/.git-prompt.sh: git-prompt.sh
    ~/.ipython: ipython
    ~/.local/bin/imgcat: imgcat
    ~/.tmux.conf: tmux.conf
    ~/.vim: vim

- shell:
    - [git submodule update --init --recursive, Installing submodules]
