#!/bin/bash

###########
# General #
###########
colorflag="--color"
# Map Escape to CapsLock
xkb_ops=`dconf read /org/gnome/desktop/input-sources/xkb-options`
if [[ $xkb_ops != *"caps:escape"* ]]; then
    dconf write /org/gnome/desktop/input-sources/xkb-options "['caps:escape']"
fi

########
# MISC #
########
M2_HOME='/opt/apache-maven-3.9.7'
GEM_HOME="$HOME/gems"
PATH="$PATH:/usr/local/bin:$HOME/.local/bin:$M2_HOME/bin:$GEM_HOME/bin"
export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
export GEM_HOME
export PATH

###########
# ALIASES #
###########
alias supr='sudo apt update; sudo apt upgrade; sudo reboot'
alias xon='xdg-open'

#############
# Functions #
#############
function dbp() {
    export MAVEN_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=8000,suspend=n"
    mvn hpi:run
}
