#!/bin/bash

#if [[ -z $(pidof ssh-agent) && -z $(pidof gpg-agent) ]]; then
if keychain > /dev/null 2>&1; then
    eval $(keychain --eval --quiet --agents ssh,gpg id_rsa)
fi

# Brew bash completion
if hash brew 2>/dev/null && [ -f `brew --prefix`/etc/bash_completion ]; then
    . `brew --prefix`/etc/bash_completion
fi

# Setting PATH for Python 3.6
# The original version is saved in .bash_profile.pysave
export PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
export BASH_SILENCE_DEPRECATION_WARNING=1
export GROOVY_HOME=/opt/homebrew/opt/groovy/libexec
export BROWSER="open /Applications/Firefox.app"
colorflag="-G"

# NOTE: Enabling :inspect mode (ergo. having headless set to false)
# with mac menu bar on top set to hide always will cause unncessary output
# to print to console when running `groovysh`
alias grvi='groovysh'
alias grv='groovysh -Djava.awt.headless=true' # Groovy with :inspect disabled
