#!/bin/bash

###########
# General #
###########
colorflag="--color"
# Map Escape to CapsLock
xkb_ops=`dconf read /org/gnome/desktop/input-sources/xkb-options`
if [[ $xkb_ops != *"caps:escape"* ]]; then
    dconf write /org/gnome/desktop/input-sources/xkb-options "['caps:escape']"
fi

########
# MISC #
########
export PATH="$PATH:/usr/local/bin:$HOME/.local/bin"
export PATH="$PATH:~/Dev/apache-maven-3.8.6/bin"
export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
# Install Ruby Gems to ~/gems
export GEM_HOME="$HOME/gems"
export PATH="$HOME/gems/bin:$PATH"

###########
# ALIASES #
###########
alias supr='sudo apt update; sudo apt upgrade; sudo reboot'

#############
# Functions #
#############
function dbp() {
    export MAVEN_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=8000,suspend=n"
    mvn hpi:run
}
