#!/bin/bash

#if [[ -z $(pidof ssh-agent) && -z $(pidof gpg-agent) ]]; then
if keychain > /dev/null 2>&1; then
    eval $(keychain --eval --quiet --agents ssh,gpg id_rsa)
fi

# Brew bash completion
if hash brew 2>/dev/null && [ -f `brew --prefix`/etc/bash_completion ]; then
    . `brew --prefix`/etc/bash_completion
fi

# Setting PATH for Python 3.6
# The original version is saved in .bash_profile.pysave
# export PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:$PATH"

# Homebrew
export BASH_SILENCE_DEPRECATION_WARNING=1
hpath="/opt/homebrew"
opath="$hpath/opt"
export PATH="$hpath/bin:$hpath/sbin:$PATH"
pkgs=(
    "bzip2"
    "curl"
    "libomp"
    "libxml2"
    "zlib"
)
pkg_configs=(
    "bzip2"
)
for pkg in "${pkgs[@]}"; do
    export PATH="$opath/$pkg/bin:$PATH"
    if [[ ! "${no_configs[@]}" =~ $pkg ]]; then
        export PKG_CONFIG_PATH="$opath/$pkg/lib/pkgconfig:$PKG_CONFIG_PATH"
    fi
    export LDFLAGS="-L$opath/$pkg/lib $LDFLAGS"
    export CPPFLAGS="-I$opath/$pkg/include $CPPFLAGS"
done
export GROOVY_HOME="$opath/groovy/libexec"


# Clang
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++


# NOTE: Enabling :inspect mode (ergo. having headless set to false)
# with mac menu bar on top set to hide always will cause unncessary output
# to print to console when running `groovysh`
# Groovy
alias grvi='groovysh'
alias grv='groovysh -Djava.awt.headless=true' # Groovy with :inspect disabled
alias bup='brew update && brew doctor && brew upgrade'


# Misc
export BROWSER="open /Applications/Firefox.app"
colorflag="-G"
