# Heavly referenced this config:
# https://gist.github.com/spicycode/1229612

unbind r
bind r source-file ~/.tmux.conf

# set -g prefix C-s
# unbind C-b

# 0 is too far from ` ;)
set -g base-index 1

set -g default-terminal "screen-256color"
set -g set-clipboard on
set -g history-limit 10000
set -g mouse on

# Automatically set window title
set-window-option -g automatic-rename on
set-option -g set-titles on
set-option -g status-position top

setw -g mode-keys vi
set -g status-keys vi

# bind-key t new-window
# bind-key v split-window -h
# bind-key s split-window -v
#
# bind-key J resize-pane -D 5
# bind-key K resize-pane -U 5
# bind-key H resize-pane -L 5
# bind-key L resize-pane -R 5
#
# bind-key M-j resize-pane -D
# bind-key M-k resize-pane -U
# bind-key M-h resize-pane -L
# bind-key M-l resize-pane -R
#
# bind-key h select-pane -L
# bind-key j select-pane -D
# bind-key k select-pane -U
# bind-key l select-pane -R
#
# # Use Alt-vim keys without prefix key to switch panes
# bind-key -n M-h select-pane -L
# bind-key -n M-j select-pane -D
# bind-key -n M-k select-pane -U
# bind-key -n M-l select-pane -R
#
# # Use Alt-arrow keys without prefix key to switch panes
# bind-key -n M-Left select-pane -L
# bind-key -n M-Right select-pane -R
# bind-key -n M-Up select-pane -U
# bind-key -n M-Down select-pane -D
#
# # Shift arrow to switch windows
# bind-key -n S-Left  previous-window
# bind-key -n S-Right next-window

# No delay for escape key press
set -sg escape-time 0

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'odedlaz/tmux-onedark-theme'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# Run this to create this folder:
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
run '~/.tmux/plugins/tpm/tpm'

# ==============================================
# OVERRIDES (Must be BELOW the run command)
# ==============================================
# Main Bar Background: Dark Grey
set -g status-style bg='#282c34',fg='#abb2bf'

# LEFT SIDE: Title "tmux"
set -g status-left "#[fg=#abb2bf,bg=#3e4452] tmux "
set -g status-left-length 20

# CENTER: Window List
# This moves the window list (1:zsh 2:vim) to the middle
set -g status-justify centre

# Right Side: Session Name
# Background: Visual Grey (#3e4452) | Foreground: Text Grey (#abb2bf)
set -g status-right "#[fg=#abb2bf,bg=#3e4452] #S "

# Active Window: Use the same Visual Grey background as the Session Name
set-window-option -g window-status-current-style bg='#3e4452',fg='#abb2bf'
set-window-option -g window-status-current-format " #I:#W "
# Inactive Windows: Blend into the main dark background
set-window-option -g window-status-style bg='#282c34',fg='#abb2bf'
set-window-option -g window-status-format " #I:#W "
